### ISSUE TITLE
4.7.6 FName cannot be converted to const TCHAR*

### ISSUE THREAD

**Issue by Algorithman** [enlight/klawr#35]
At least for me building UE4.7.6 with klawr complains in K2_LineTraceComponent in PrimitiveComponent.klawr.h.
(FName cant be converted to const TCHAR*)

Since this file is generated i'm not entirely sure where to find the cause for this.
But if you throw me a bone i'm happy to hunt this one down :)

**Comment by enlight** [comment]
I'll take a look at this today.

**Comment by Algorithman** [comment]
I'm also getting a c# compile error, which i cant see since the window it dissapears instantly and i cant find a logfile for this task. Doesnt break UBT tho but results in a crash when the editor starts.

**Comment by enlight** [comment]
Yeah I've noticed that too, you can see the actual error by running `Engine\Intermediate\ProjectFiles\Klawr\Build.bat` from a console window. There's a file being generated that shouldn't be, don't know why yet.

**Comment by Algorithman** [comment]
The TestActor errors out, cos K2_GetWorld apparently doesnt exist

**Comment by Algorithman** [comment]
yeah, got it running

2 things:
FName conversion to const TCHAR* 
and
copying of the Klawr.UnrealEngine.dll/pdb into UnrealEngine\Engine\Binaries\Win64\Klawr\Assemblies needed to be fixed.

i post a fix later after i checked functionality a bit. But at least the editor runs :)

**Comment by enlight** [comment]
Cool. I'm working on solving the `FName` to `const TCHAR*` issue by marshaling `FName` to `FScriptName`. How did you get around it?

**Comment by Algorithman** [comment]
Since i'm not the c++ guy (therefore i want this working, lol) i changed in the K2_LineTraceComponent  the conversion to 

BoneName = *(Param.BoneName.ToString());

To be more explicit: 
KlawrNativeWrapperGenerator.cpp

in GenerateFunctionWrapper i added a if (param->IsA(UNameProperty::StaticClass())) and there i added TEXT"%s = *(Params.%s.ToString());"), *param->GetName(), *param->GetName());
This took care of the conversion (i hope i dont mess up memory stuff with this one tho)

oh and the template is missing the 
using Klawr.ClrHost.Managed.SafeHandles;

**Comment by Algorithman** [comment]
full file: http://pastebin.com/rtY89wCg

**Comment by Algorithman** [comment]
Do you remember if the AActor::GetWorld() always had the 'const' at the end?
I think this would still be an issue to solve

**Comment by enlight** [comment]
No clue about `AActor::GetWorld()`, sorry.

**Comment by Algorithman** [comment]
It was in your TestActor.cs (K2_GetWorld). but K2_GetWorld isnt created, so i thought they might have changed the function designation.

**Comment by enlight** [comment]
Quite possible, I haven't been paying a lot of attention to new releases in the past few months.

**Comment by Algorithman** [comment]
i probably wont need getworld in the scripts anyway, i want to use it for level calculation/creation where i just dont have the stomach for c++

**Comment by Algorithman** [comment]
btw very nice wrapper generator. You have my thanks :)

**Comment by Algorithman** [comment]
Is exposing variables/functions from c# to blueprint implemented already?

**Comment by enlight** [comment]
Unfortunately not, those are still open issues. I've just committed a fix for the generator to deal with `UPrimitiveComponent::K2_LineTraceComponent()`. I'll probably take a look at fixing the generated C# project tomorrow.

**Comment by Algorithman** [comment]
I take a look at the exposing variables issue. Maybe i can come up with a solution (shouldnt be that hard)

**Comment by enlight** [comment]
Good luck :), see issues #26 and #27.

**Comment by enlight** [comment]
All build issues should be resolved at this point, UE 4.8 is now the minimum supported version.
