### ISSUE TITLE
Update to UE 4.8.1

### ISSUE THREAD

**Issue by enlight** [enlight/klawr#36]
There've been some changes to how Unreal Header Tool finds script generator plugins, [here's the relevant revision](https://github.com/EpicGames/UnrealEngine/commit/920d8e07d1055f2f119563d71c04d4ff35229f76).

**Comment by enlight** [comment]
Fixed project file generation for UE 4.8 in afd1c3a7a9c4fc3ef18bc15e9dcfe91a07404945
More fixes to follow.

**Comment by Algorithman** [comment]
Thx vadim, i cant get it to compile yet :( 
spent the whole sunday with tryin ...

**Comment by enlight** [comment]
Yeah, I've made some fixes to account for changes in UE 4.8, but I've got an issue with Unreal Header Tool failing to load the Klawr generator plugin. I'm hoping I can get that sorted out later today.

**Comment by enlight** [comment]
Unfortunately I didn't have time to fix everything today, the code generator builds and runs now, but the generated C# wrappers project still fails to build due to this error:
>Engine\Plugins\Klawr\KlawrRuntimePlugin\Intermediate\Build\Win64\UE4Editor\Inc\KlawrRuntimePlugin\PlayerCameraManager.cs(250,109): error CS0311: The type 'Klawr.UnrealEngine.TSubclassOf<Klawr.UnrealEngine.U CameraModifier>' cannot be used as type parameter 'T' in the generic type or method 'Klawr.ClrHost.Managed.Collections.ObjectArrayProperty<T>'. There is no implicit reference conversion from 'Klawr.UnrealEngine.TSubclassOf<Klawr.UnrealEn gine.UCameraModifier>' to 'Klawr.UnrealEngine.UObject'.

**Comment by Algorithman** [comment]
cant compile the native clrhost atm.
Error	2	error C2857: '#include' statement specified with the /Ycstdafx.h command-line option was not found in the source file	c:\github\klawr\engine\source\thirdparty\klawr\clrhostnative\private\klawrclrhostpch.cpp	7	1	Klawr.ClrHost.Native

**Comment by Algorithman** [comment]
As for the TSubClassOf part, we shouldnt need it on the c# side anyway, since c# is type-safe already

**Comment by enlight** [comment]
The C# wrappers project now builds, but I haven't checked if the editor/runtime plugins work.

**Comment by Algorithman** [comment]
Dunno if you seen my msgs on irc, but i prepared a bit on https://github.com/Algorithman/klawr/commit/8b3567f4845795ac9645b6ed859d5456a9889b26

**Comment by enlight** [comment]
OK, the editor plugin now builds without errors/warnings, had to make the same Slate & BlueprintCompiler changes you've made in your branch. The editor plugin still doesn't function correctly, it fails to build the GameScripts assembly, so that's the next thing I'm going to be looking at.

**Comment by enlight** [comment]
Fixed the GameScripts assembly not building, so everything builds and runs now, for me anyway :). Well kinda runs, I got a crash after adding a few Klawr BP components to an actor and recompiling a few times. Fun times ahead.

**Comment by Algorithman** [comment]
Lucky you :)
Still got missing .generated.h files error on building UE4 with klawr (on 4.8.1-release and 4.8.2-release)

**Comment by enlight** [comment]
For future reference compiler errors about missing `.generated.h` files are usually caused by missing dependency modules, to resolve such errors figure out which module the header file attempting to include the `.generated.h` file is from and then add that module to `PrivateDependencyModuleNames` in `KlawrRuntimePlugin.Build.cs`.
