### ISSUE TITLE
Does not work with source build as of today

### ISSUE THREAD

**Issue by 06needhamt** [enlight/klawr#47]

**Comment by enlight** [comment]
Which branch were you trying to build? Were you using VS 2015?

VS 2015 seems to be picked by default in 4.10, so I'll have to update the VS 2013 projects to the new version.

**Comment by 06needhamt** [comment]
Yes I was using vs2015 and building the master branch. 

I can't give you any more info right now as I am on vacation until next week.

I will contact you when I get home

**Comment by 06needhamt** [comment]
Here is the error list when building using today's 5th November 2015 master branch.
![klawr](https://cloud.githubusercontent.com/assets/4162227/10970567/72531f02-83c7-11e5-8b18-488f323c21c0.png)

**Comment by enlight** [comment]
OK, thanks.

**Comment by 06needhamt** [comment]
Any idea when it will be fixed?

**Comment by 06needhamt** [comment]
Still not working with today's source from master branch. 
Any idea when it will be fixed?
Thanks

**Comment by enlight** [comment]
I'll try to sort it out this weekend.

**Comment by enlight** [comment]
I have it building with the UE 4.10.0 release now, aside from a deprecation warning I haven't had to fix much, and I did not see any of those errors you encountered.

**Comment by Algorithman** [comment]
Me neither, only thing was the HasAnyPackageFlags

**Comment by 06needhamt** [comment]
i have modified the code to remove the build errors i was experiencing. bit one error still remains Error   C1083   Cannot open include file: 'Network Replay Streaming.h' which is in one of the engine source code modules so i guess its an engine bug not a bug with this plugin. i have created a pull request containing my changes here https://github.com/enlight/klawr/pull/49 although i don't know if it is a bug with the plugin or whether i have not set something up properly.

Hope this helps you
