### ISSUE TITLE
Libraries ok, Plugins no:(

### ISSUE THREAD

**Issue by ghost** [enlight/klawr#51]
Hi, Vadim. First of all I want to thank you for creating this project, I would really like to try it in fact. I was not able to setup it right, as I see UE has changed since time you published your instructions. Do you have any plans to update it and explain how to make it work with current UE?

Best wishes, Alexey

**Comment by enlight** [comment]
Hi. Unfortunately I don't have any plans to resume work on this project in the near future. The fork at https://github.com/Algorithman/klawr was quite active at one point, but I guess @Algorithman has been busy with other things lately. Now that Microsoft has taken over Xamarin I wonder if we'll see a resurrection of Mono for UE4 at some point.
